sudo: false
dist: trusty

language: java

refs:
  - &build_ref
    stage: Build
    script:
      # Fail the script if any command fails
      - set -o errexit
      # Build the base and JMH bundles
      - tools/ci/cache-get.sh
      - tools/ci/build-base.sh
      - tools/ci/build-jmh.sh
      - tools/ci/stop-sbt.sh
      - tools/ci/check-jmh.sh
      - tools/ci/cache-put.sh

  - &bench_ref
    stage: Bench
    script:
      # Fail the script if any command fails
      - set -o errexit
      # Test the base and JMH bundles
      - tools/ci/cache-get.sh
      - tools/ci/build-base.sh
      - tools/ci/build-jmh.sh
      - tools/ci/stop-sbt.sh
      - tools/ci/check-jmh.sh
      - tools/ci/bench-base.sh
      - tools/ci/bench-jmh.sh

jobs:
  include:
    # Pre-flight check on OS X (most fragile)
    - stage: Check
      name: "OS X, JDK9, Oracle"
      os: osx
      osx_image: xcode9.3
      jdk: oraclejdk9
      script:
        # Fail the script if any command fails
        - set -o errexit
        - tools/ci/check-encoding.sh
        - tools/ci/check-sbt.sh
        - tools/ci/check-formatting.sh
        - tools/ci/build-base.sh
        - tools/ci/stop-sbt.sh
        - tools/ci/check-markdown.sh
        - tools/ci/cache-put.sh

    # Build and cache with different JDKs
    - <<: *build_ref
      name: "OS X, JDK9, Oracle"
      os: osx
      osx_image: xcode9.3
      jdk: oraclejdk9

    - <<: *build_ref
      name: "Linux, JDK8, OpenJDK"
      jdk: openjdk8

    - <<: *build_ref
      name: "Linux, JDK8, Oracle"
      jdk: oraclejdk8

    - <<: *build_ref
      name: "Linux, JDK11, OpenJDK"
      jdk: openjdk11

    - <<: *build_ref
      name: "Linux, JDK11, Oracle"
      jdk: oraclejdk11

    - <<: *build_ref
      name: "Linux, JDK11, OpenJ9"
      env:
        - USE_JDK=openj9jdk11

    # Test benchmarks with different JDKs
    - <<: *bench_ref
      name: "OS X, JDK9, Oracle"
      os: osx
      osx_image: xcode9.3
      jdk: oraclejdk9

    - <<: *bench_ref
      name: "Linux, JDK8, OpenJDK"
      jdk: openjdk8

    - <<: *bench_ref
      name: "Linux, JDK8, Oracle"
      jdk: oraclejdk8

    - <<: *bench_ref
      name: "Linux, JDK11, OpenJDK"
      jdk: openjdk11

    - <<: *bench_ref
      name: "Linux, JDK11, Oracle"
      jdk: oraclejdk11

    - <<: *bench_ref
      name: "Linux, JDK11, OpenJ9"
      env:
        - USE_JDK=openj9jdk11

stages:
  - Check
  - Build
  - Bench

before_script:
  # Setup JDK indicated in USE_JDK.
  - source tools/ci/setup-jdk.sh

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.prebuilt
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  # (see https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html#Caching)
  - find $HOME/{.ivy2,.sbt} -type f -name "*.lock" -print -delete
  - find $HOME/.sbt -type f -name "*-libswoval-*" -print -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
