name: build
on: [push, pull_request]
jobs:
  linux:
    strategy:
      matrix:
        image:
          - openjdk8
          - openjdk9
          - openjdk10
          - openjdk11
          - openjdk12
          - openj9-openjdk8
          - openj9-openjdk11
          - openj9-openjdk16
    runs-on: ubuntu-latest
    container: "renaissancebench/buildenv:${{ matrix.image }}"
    continue-on-error: true
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Install dependencies
        shell: bash
        run: "tools/ci/install-deps.sh"

      - name: Environment configuration
        shell: bash
        run: "tools/ci/show-env.sh"

      - name: Build base
        shell: bash
        run: "tools/ci/build-base.sh"

      - name: Build JMH
        shell: bash
        run: "tools/ci/build-jmh.sh"

      - name: Stop SBT
        shell: bash
        run: "tools/ci/stop-sbt.sh"

      - name: Check JMH
        shell: bash
        run: "tools/ci/check-jmh.sh"

      - name: Run the suite
        shell: bash
        run: "tools/ci/bench-base.sh"

      - name: Run the suite with JMH
        shell: bash
        run: "tools/ci/bench-jmh.sh"

  other:
    strategy:
      matrix:
        java: [ '8' ] #, '11', '13', '15' ]
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup correct Java version
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - name: Environment configuration
        shell: bash
        run: "tools/ci/show-env.sh"

      - name: Build base
        shell: bash
        run: "tools/ci/build-base.sh"

      - name: Build JMH
        shell: bash
        run: "tools/ci/build-jmh.sh"

      - name: Stop SBT
        shell: bash
        run: "tools/ci/stop-sbt.sh"

      - name: Check JMH
        shell: bash
        run: "tools/ci/check-jmh.sh"

      - name: Run the suite
        shell: bash
        run: "tools/ci/bench-base.sh"

      - name: Run the suite with JMH
        shell: bash
        run: "tools/ci/bench-jmh.sh"
