name: build
on: [push, pull_request]
jobs:
  jdks-on-linux:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            image: openjdk:11.0.11-jdk
          - os: ubuntu-latest
            image: adoptopenjdk:11.0.10_9-jdk-openj9-0.24.0
          - os: windows-latest
            image: openjdk:11.0.11-jdk
#          - os: ubuntu-latest
#            image: openjdk:10.0.2-jdk
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Environment configuration
        shell: bash
        run: |
          java -version && javac -version
#      - name: Assembly
#        shell: bash
#        run: |
#          ./tools/sbt/bin/sbt assembly
