name: build
on: [push, pull_request]
jobs:
  linux:
    strategy:
      matrix:
        image:
          - openjdk:10.0.2-jdk
          - openjdk:11.0.11-jdk
          - adoptopenjdk:11.0.10_9-jdk-openj9-0.24.0
          - openjdk:12.0.2-jdk
          - openjdk:13.0.2-jdk
          - openjdk:14.0.2-jdk
          - openjdk:15.0.2-jdk
          - openjdk:16.0.1-jdk
          - openjdk:17-jdk
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Environment configuration
        shell: bash
        run: |
          java -version && javac -version
      - name: Assembly
        shell: bash
        run: |
          ./tools/sbt/bin/sbt assembly
          java -jar ./target/renaissance-gpl-0.11.0.jar --raw-list

  windows:
    strategy:
      matrix:
        java: [ '8', '11', '13', '15' ]
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup correct Java version
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Environment configuration
        shell: bash
        run: |
          java -version && javac -version
      - name: Assembly
        shell: bash
        run: |
          ./tools/sbt/bin/sbt assembly
          java -jar ./target/renaissance-gpl-0.11.0.jar --raw-list
