name: Linux
on: [push, pull_request]
jobs:
  linux:
    strategy:
      matrix:
        image:
          - openjdk8
          - openjdk9
          - openjdk10
          - openjdk11
          - openjdk12
          - openjdk13
          - openjdk14
          - openjdk15
          - openjdk16
          - openjdk18-ea
          - openjdk19-ea
          - openj9-openjdk8
          - openj9-openjdk11
          - openj9-openjdk16
    runs-on: ubuntu-latest
    continue-on-error: true
    container: "renaissancebench/buildenv:${{ matrix.image }}"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}

      - name: Environment configuration
        shell: bash
        run: tools/ci/pre-show-env.sh

      - name: Build base & JMH bundles
        shell: bash
        run: tools/ci/build-both.sh

      - name: Check JMH bundle
        shell: bash
        run: tools/ci/check-jmh.sh

      - name: Run the suite
        shell: bash
        run: tools/ci/bench-base.sh

      - name: Run the suite in standalone mode
        shell: bash
        run: tools/ci/bench-standalone.sh

      - name: Run the suite with JMH
        shell: bash
        run: tools/ci/bench-jmh.sh
