name: Linux
on: [push, pull_request]
jobs:
  linux:
    strategy:
      matrix:
        image:
          - openjdk8
          - openjdk9
          - openjdk10
          - openjdk11
          - openjdk12
          - openjdk13
          - openjdk14
          - openjdk15
          - openjdk16
          - openj9-openjdk8
          - openj9-openjdk11
          - openj9-openjdk16
    runs-on: ubuntu-latest
    container: "renaissancebench/buildenv:${{ matrix.image }}"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Environment configuration
        shell: bash
        run: "tools/ci/pre-show-env.sh"

      - name: Build base
        shell: bash
        run: "tools/ci/build-base.sh"

      - name: Build JMH
        shell: bash
        run: "tools/ci/build-jmh.sh"

      - name: Stop SBT
        shell: bash
        run: "tools/ci/stop-sbt.sh"

      - name: Check JMH
        shell: bash
        run: "tools/ci/check-jmh.sh"

      - name: Run the suite
        shell: bash
        run: "tools/ci/bench-base.sh"

      - name: Run the suite with JMH
        shell: bash
        run: "tools/ci/bench-jmh.sh"
