name: "Windows (legacy)"
on:
  workflow_run:
    workflows: [Main]
    types: [completed]
jobs:
  windows:
    strategy:
      matrix:
        java: [ '8', '11' , '13', '15' ]
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    continue-on-error: true
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup correct Java version
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - name: Environment configuration
        shell: bash
        run: tools/ci/pre-show-env.sh

      - name: Build both base & JMH bundles
        shell: bash
        run: tools/sbt/bin/sbt --batch 'renaissance/package;renaissanceJmh/package'

      - name: Check JMH bundle
        shell: bash
        run: tools/ci/check-jmh.sh

      - name: Dummy run and environment configuration
        shell: bash
        run: tools/ci/bench-show-env.sh

      - name: Run the suite
        shell: bash
        run: tools/ci/bench-base.sh

      - name: Run the suite in standalone mode
        shell: bash
        run: tools/ci/bench-standalone.sh

      - name: Run the suite with JMH
        shell: bash
        run: tools/ci/bench-jmh.sh
